# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('asset_prefix', models.CharField(max_length=100)),
            ],
        ),
    ]
