# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cholofighter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('asset_prefix', models.CharField(max_length=100)),
            ],
        ),
    ]
