# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cholofighter', '0002_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
